version: "3.8"

services:
  db:
    env_file: .env
    image: postgres:13.1-alpine
    volumes:
      - ./volumes/:/docker-entrypoint-initdb.d/

  redis:
    image: redis:6.0.10-alpine

  web:
    image: logicall_web:latest
    env_file: .env
    depends_on:
      - "db"
    ports:
      - "80:3000"
