version: '3.8'

services:

  mysql:
    container_name: mysql
    build:
      context: ./mysql
    expose: 
      - 3306

  adminer:
    image: "adminer:4.7.7"
    container_name: adminer
    expose: 
      - 8080

  node:
    container_name: node
    build:
      context: ./node
    expose: 
      - 3000
    environment: 
      - NODE_ENV=production
    tty: true

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    volumes:
      - ./nginx/:/etc/nginx/site-available/
    ports:
      - 80:80
      - 443:443
    tty: true
