version: '3.8'

services:

  mysql:
    container_name: mysql
    # command: --default-authentication-plugin=mysql_native_password
    build:
      context: ./mysql
      args:
        MYSQL_DATABASE: classicmodels
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: docker
        MYSQL_PASSWORD: docker
    volumes:
      - ./mysql/data/:/docker-entrypoint-initdb.d
    expose: 
      - 3306

  node:
    container_name: node
    build:
      context: ./node
    expose: 
      - 3000
    tty: true
    depends_on: 
      - mysql

  # vue:
  #   container_name: vue
  #   build: 
  #     context: ./vue
  #   expose: 
  #     - 8080
  #   tty: true

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    volumes:
      - ./nginx/:/etc/nginx/site-available/
      # - ./vue/dist/:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
    tty: true
    depends_on: 
      - node
