version: "3.8"

services:
  db:
    container_name: db
    ports:
      - 5432:5432

  redis:
    container_name: redis
    ports:
      - 6379:6379

  web:
    container_name: web
    build:
      context: ./web
