name: Autofix Linting

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Autofix Linting
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-versions: "12.x"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run Lint Check
        run: yarn lint

      - name: Commit Autofix
        uses: EndBug/add-and-commit@v5
        with:
          message: "Autofix Linting"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
